In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import sys

In [104]:
d1 = pd.read_csv("../data/raw/PTF_SMF_ve_SDF_Listeleme-01012024-01012025.csv",sep=";")  #data from 2024
d2 = pd.read_csv("../data/raw/PTF_SMF_ve_SDF_Listeleme-01012025-20122025.csv",sep=";")  #data from 2025
epias_data = pd.concat([d1,d2], ignore_index=True)                                #combine data 2024-2025

epias_data.head()

,Tarih,Saat,PTF,SMF,Pozitif Dengesizlik Fiyatı (TL/MWh),Negatif Dengesizlik Fiyatı (TL/MWh),SMF Yön
0,01.01.2024,00:00,"1.299,98","560,00","543,20","1.338,98",Enerji Fazlası
1,01.01.2024,01:00,"1.299,98","1.299,98","1.260,98","1.338,98",Enerji Fazlası
2,01.01.2024,02:00,"1.248,54","1.248,54","1.211,08","1.286,00",Enerji Fazlası
3,01.01.2024,03:00,"1.299,98","1.250,00","1.212,50","1.338,98",Enerji Fazlası
4,01.01.2024,04:00,"1.200,00","1.150,00","1.115,50","1.236,00",Enerji Fazlası

In [105]:
epias_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17304 entries, 0 to 17303
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Tarih                                17304 non-null  object
 1   Saat                                 17304 non-null  object
 2   PTF                                  17304 non-null  object
 3   SMF                                  17292 non-null  object
 4   Pozitif Dengesizlik Fiyatı (TL/MWh)  17292 non-null  object
 5   Negatif Dengesizlik Fiyatı (TL/MWh)  17292 non-null  object
 6   SMF Yön                              17292 non-null  object
dtypes: object(7)
memory usage: 946.4+ KB

In [106]:
null_data = epias_data[epias_data.isnull().any(axis=1)]

display(null_data)

,Tarih,Saat,PTF,SMF,Pozitif Dengesizlik Fiyatı (TL/MWh),Negatif Dengesizlik Fiyatı (TL/MWh),SMF Yön
17292,20.12.2025,12:00,"2.297,18",NaN,NaN,NaN,NaN
17293,20.12.2025,13:00,"2.575,78",NaN,NaN,NaN,NaN
17294,20.12.2025,14:00,"2.696,78",NaN,NaN,NaN,NaN
17295,20.12.2025,15:00,"2.950,01",NaN,NaN,NaN,NaN
17296,20.12.2025,16:00,"3.393,44",NaN,NaN,NaN,NaN
17297,20.12.2025,17:00,"3.400,00",NaN,NaN,NaN,NaN
17298,20.12.2025,18:00,"3.400,00",NaN,NaN,NaN,NaN
17299,20.12.2025,19:00,"3.252,93",NaN,NaN,NaN,NaN
17300,20.12.2025,20:00,"2.950,00",NaN,NaN,NaN,NaN
17301,20.12.2025,21:00,"3.400,00",NaN,NaN,NaN,NaN
17302,20.12.2025,22:00,"3.077,77",NaN,NaN,NaN,NaN
17303,20.12.2025,23:00,"2.946,00",NaN,NaN,NaN,NaN

In [107]:
epias_data.dropna(inplace=True)

In [108]:
epias_data.describe().T

                                     count unique           top   freq
Tarih                                17292    720    01.01.2025     48
Saat                                 17292     24         00:00    721
PTF                                  17292   5389      3.000,00    944
SMF                                  17292   3565      3.400,00   2427
Pozitif Dengesizlik Fiyatı (TL/MWh)  17292   4889      3.298,00    896
Negatif Dengesizlik Fiyatı (TL/MWh)  17292   4435      3.502,00   2468
SMF Yön                              17292      3  Enerji Açığı  11082

In [109]:
num_cols = epias_data.columns.drop(['Tarih', 'Saat', "SMF Yön"])
for col in num_cols:
    epias_data[col] = epias_data[col].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
    epias_data[col] = pd.to_numeric(epias_data[col])

In [110]:
epias_data.describe().T

,count,mean,std,min,25%,50%,75%,max
PTF,17292.0,2418.296786,756.303117,0.0,2060.9975,2550.00,2982.0000,3400.0
SMF,17292.0,2342.241533,964.878141,0.0,1800.0000,2691.00,3000.0000,3400.0
Pozitif Dengesizlik Fiyatı (TL/MWh),17292.0,2098.960608,902.630358,0.0,1646.0900,2287.26,2836.3675,3298.0
Negatif Dengesizlik Fiyatı (TL/MWh),17292.0,2674.561313,761.296739,0.0,2374.1400,2781.00,3090.0000,3502.0

In [111]:
epias_data.head(20)

,Tarih,Saat,PTF,SMF,Pozitif Dengesizlik Fiyatı (TL/MWh),Negatif Dengesizlik Fiyatı (TL/MWh),SMF Yön
0,01.01.2024,00:00,1299.98,560.00,543.20,1338.98,Enerji Fazlası
1,01.01.2024,01:00,1299.98,1299.98,1260.98,1338.98,Enerji Fazlası
2,01.01.2024,02:00,1248.54,1248.54,1211.08,1286.00,Enerji Fazlası
3,01.01.2024,03:00,1299.98,1250.00,1212.50,1338.98,Enerji Fazlası
4,01.01.2024,04:00,1200.00,1150.00,1115.50,1236.00,Enerji Fazlası
5,01.01.2024,05:00,1200.00,1200.00,1164.00,1236.00,Enerji Fazlası
6,01.01.2024,06:00,1248.54,1248.54,1211.08,1286.00,Dengede
7,01.01.2024,07:00,1299.99,1299.99,1260.99,1338.99,Enerji Fazlası
8,01.01.2024,08:00,1299.99,499.99,484.99,1338.99,Enerji Fazlası
9,01.01.2024,09:00,1399.98,5.00,4.85,1441.98,Enerji Fazlası
10,01.01.2024,10:00,1299.99,1.20,1.16,1338.99,Enerji Fazlası
11,01.01.2024,11:00,1200.00,1.19,1.15,1236.00,Enerji Fazlası
12,01.01.2024,12:00,1000.00,1.88,1.82,1030.00,Enerji Fazlası
13,01.01.2024,13:00,1199.99,500.00,485.00,1235.99,Enerji Fazlası
14,01.01.2024,14:00,1299.98,1299.98,1260.98,1338.98,Dengede
15,01.01.2024,15:00,1299.98,1299.98,1260.98,1338.98,Enerji Fazlası
16,01.01.2024,16:00,1915.15,2400.00,1857.70,2472.00,Enerji Açığı
17,01.01.2024,17:00,2525.00,2525.00,2449.25,2600.75,Enerji Açığı
18,01.01.2024,18:00,2601.44,2601.44,2523.40,2679.48,Enerji Açığı
19,01.01.2024,19:00,2200.01,2200.01,2134.01,2266.01,Dengede

In [112]:
epias_data.reset_index(drop=True, inplace=True)
epias_data.index = pd.to_datetime(epias_data['Tarih'] + ' ' + epias_data['Saat'], dayfirst=True)

epias_data.head()

,Tarih,Saat,PTF,SMF,Pozitif Dengesizlik Fiyatı (TL/MWh),Negatif Dengesizlik Fiyatı (TL/MWh),SMF Yön
2024-01-01 00:00:00,01.01.2024,00:00,1299.98,560.00,543.20,1338.98,Enerji Fazlası
2024-01-01 01:00:00,01.01.2024,01:00,1299.98,1299.98,1260.98,1338.98,Enerji Fazlası
2024-01-01 02:00:00,01.01.2024,02:00,1248.54,1248.54,1211.08,1286.00,Enerji Fazlası
2024-01-01 03:00:00,01.01.2024,03:00,1299.98,1250.00,1212.50,1338.98,Enerji Fazlası
2024-01-01 04:00:00,01.01.2024,04:00,1200.00,1150.00,1115.50,1236.00,Enerji Fazlası

In [113]:
epias_data.index

DatetimeIndex(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
               '2024-01-01 02:00:00', '2024-01-01 03:00:00',
               '2024-01-01 04:00:00', '2024-01-01 05:00:00',
               '2024-01-01 06:00:00', '2024-01-01 07:00:00',
               '2024-01-01 08:00:00', '2024-01-01 09:00:00',
               ...
               '2025-12-20 02:00:00', '2025-12-20 03:00:00',
               '2025-12-20 04:00:00', '2025-12-20 05:00:00',
               '2025-12-20 06:00:00', '2025-12-20 07:00:00',
               '2025-12-20 08:00:00', '2025-12-20 09:00:00',
               '2025-12-20 10:00:00', '2025-12-20 11:00:00'],
              dtype='datetime64[ns]', length=17292, freq=None)

In [114]:
epias_data["month"] = epias_data.index.month
epias_data["day"] = epias_data.index.day_name()


epias_data.loc[epias_data['month'].isin([12, 1, 2]), 'season'] = 'winter'
epias_data.loc[epias_data['month'].isin([3, 4, 5]), 'season'] = 'spring'
epias_data.loc[epias_data['month'].isin([6, 7, 8]), 'season'] = 'summer'
epias_data.loc[epias_data['month'].isin([9, 10, 11]), 'season'] = 'autumn'

In [115]:
epias_data

,Tarih,Saat,PTF,SMF,Pozitif Dengesizlik Fiyatı (TL/MWh),Negatif Dengesizlik Fiyatı (TL/MWh),SMF Yön,month,day,season
2024-01-01 00:00:00,01.01.2024,00:00,1299.98,560.00,543.20,1338.98,Enerji Fazlası,1,Monday,winter
2024-01-01 01:00:00,01.01.2024,01:00,1299.98,1299.98,1260.98,1338.98,Enerji Fazlası,1,Monday,winter
2024-01-01 02:00:00,01.01.2024,02:00,1248.54,1248.54,1211.08,1286.00,Enerji Fazlası,1,Monday,winter
2024-01-01 03:00:00,01.01.2024,03:00,1299.98,1250.00,1212.50,1338.98,Enerji Fazlası,1,Monday,winter
2024-01-01 04:00:00,01.01.2024,04:00,1200.00,1150.00,1115.50,1236.00,Enerji Fazlası,1,Monday,winter
...,...,...,...,...,...,...,...,...,...,...
2025-12-20 07:00:00,20.12.2025,07:00,3130.00,2321.00,2251.37,3223.90,Enerji Fazlası,12,Saturday,winter
2025-12-20 08:00:00,20.12.2025,08:00,3400.00,3400.00,3298.00,3502.00,Enerji Açığı,12,Saturday,winter
2025-12-20 09:00:00,20.12.2025,09:00,2892.00,3400.00,2805.24,3502.00,Enerji Açığı,12,Saturday,winter
2025-12-20 10:00:00,20.12.2025,10:00,2469.99,2321.00,2251.37,2544.09,Enerji Fazlası,12,Saturday,winter
2025-12-20 11:00:00,20.12.2025,11:00,2604.99,2994.88,2526.84,3084.73,Enerji Açığı,12,Saturday,winter

In [116]:
epias_data.to_pickle("../data/processed/epias_cleaned.pkl")